apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: springcommunity/spring-petclinic-customers-service
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 5; done;']
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until nc -z discovery-server 8761; do echo waiting for discovery-server; sleep 5; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  ports:
    - port: 8081
      targetPort: 8081

