apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: springcommunity/spring-petclinic-discovery-server
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
      initContainers:
        - name: wait-for-config-server
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 5; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761

