apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4.5
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-upetclinic", "-ppetclinic"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.16.0
          ports:
            - containerPort: 9104
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          args:
            - --mysqld.username=petclinic
            - --mysqld.address=localhost:3306
          resources:
            limits:
              memory: 128Mi
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
    - name: metrics
      port: 9104
      targetPort: 9104

